name: Boot camp 2020

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubunto-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12     
    - name: installing surge
      run: npm install --global surge
    - name: deploying using surge
      run: surge ./ waji-bootcampclass1.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
      
